### ISSUE TITLE
Research Wayland solution 

### ISSUE THREAD

**Issue by DavidLarsson** [psibi/emacs-everywhere#2]
Long-term it seems to be a good idea to try to find a solution for making Emacs Everywhere work on Wayland. Any findings could be posted here. Is that OK?

**Comment by psibi** [comment]
Sounds good. Right now, it seems there is no alternative for xdotool for wayland.

**Comment by ulysses4ever** [comment]
There seems to be a Wayland analog to xdotool now: https://github.com/atx/wtype But it seems less powerful currently. With Wayland's security goals, I'm not sure it's even possible to do what xdotool does in principle.

**Comment by tekakutli** [comment]
> Sounds good. Right now, it seems there is no alternative for xdotool for wayland.
there is another wayland alternative: ydotool

**Comment by Seme4eg** [comment]
Maybe [ydotool](https://github.com/ReimuNotMoe/ydotool) or [dotool](https://git.sr.ht/~geb/dotool) referenced on xdotool github page will do the trick?

**Comment by psibi** [comment]
The master branch supports wayland.
